/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./hooks/**/*.{js,jsx,ts,tsx}",
    "./lib/**/*.{js,jsx,ts,tsx}",
    "./services/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        poppins: ["Poppins_400Regular"],
        "poppins-medium": ["Poppins_500Medium"],
        "poppins-semibold": ["Poppins_600SemiBold"],
        "poppins-bold": ["Poppins_700Bold"],
        inter: ["Inter_400Regular"],
        "inter-medium": ["Inter_500Medium"],
        "inter-semibold": ["Inter_600SemiBold"],
        "inter-bold": ["Inter_700Bold"],
      },
      colors: {
        "bolt-blue": "#0052CC",
        "bolt-light": "#E8F0FE",
        "bolt-primary-dark": "#003A99",
        "bolt-yellow": "#FFD700",
        "bolt-mint": "#22C55E",
        "bolt-purple": "#8B5CF6",
        "bolt-red": "#EF4444",
        "bolt-graphite": "#1A1A1A",
        "bolt-slate": "#6B7280",
        "bolt-surface": "#F9FAFB",
        "bolt-card": "#FFFFFF",
        "bolt-border": "#E5E7EB",
        "bolt-divider": "#F3F4F6",
        "bolt-disabled": "#D1D5DB",
        "bolt-success-text": "#15803D",
        "bolt-success-bg": "#F0FDF4",
        "bolt-success-border": "#BBF7D0",
        "bolt-danger-text": "#DC2626",
        "bolt-danger-bg": "#FEF2F2",
        "bolt-danger-border": "#FECACA",
        "bolt-warning-text": "#D97706",
        "bolt-warning-bg": "#FFFBEB",
        "bolt-warning-border": "#FDE68A",
      },
      fontSize: {
        "2xs": ["9px", { lineHeight: "13px" }],
        xs: ["11px", { lineHeight: "16px" }],
        sm: ["13px", { lineHeight: "18px" }],
        base: ["15px", { lineHeight: "22px" }],
        lg: ["17px", { lineHeight: "24px" }],
        xl: ["20px", { lineHeight: "28px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "3xl": ["30px", { lineHeight: "38px" }],
        hero: ["36px", { lineHeight: "44px" }],
      },
      borderRadius: {
        "2xl": "16px",
        "3xl": "24px",
      },
      letterSpacing: {
        widest: "0.12em",
      },
    },
  },
  plugins: [],
};
